### ISSUE TITLE
Is there a conf for pressure, spool time, etc?

### ISSUE THREAD

**Issue by cykelstativet** [DDev247/engine-sim#10]
Looked around, but I'm an idiot. I saw you change bar in the video.

**Comment by DDev247** [comment]
Its not possible, yet. BUT you can regulate the pressure by pressing `0` and scrolling.

**Comment by cykelstativet** [comment]
Ah, thanks! I really recommend wring these keybinds down somewhere (i just now started spamming keys and noticed others) so people won't bother you like i did.

**Comment by DDev247** [comment]
> Ah, thanks! I really recommend wring these keybinds down somewhere (i just now started spamming keys and noticed others) so people won't bother you like i did.

These are actually written in the readme, but I understand if you didn't see them.
[Here](https://github.com/DDev247/engine-sim#how-do-i-use-it) is the readme part which specifies the keybinds.
